### ISSUE TITLE
话说本地用了ss/ssr 端口开在1080 的话 怎么配置 才能 让所有流量到fiddler 

### ISSUE THREAD

**Issue by aiastia** [xxxily/Fiddler-plus#2]
想实现 所有流量到 fiddler 然和在转发到 ss/ssr 客户端。 试了在 iddler 菜单 -> Tools -> fiddler Options ->Gateway -> Manual Proxy Configuration 这样 不能翻墙……

**Comment by wdsjxh** [comment]
proxifer把应用流量转发一下
